### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/popt#1]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by ignatenkobrain** [comment]
Are there any important ones?

**Comment by pmatilai** [comment]
I don't think any of us really even knows what's in there (I certainly don't) and I've heard too much talk about going to 2.0 and introducing ABI/API incompatibilities to do a blind release of whatever is there.

For the time being, we have no plans beyond simply providing a shelter for popt: a home for the code, and for people to submit bugs and pull requests.

**Comment by pmatilai** [comment]
After looking at the post-1.16 stuff in a bit more detail, I think the way forward is to branch off at the widely used 1.16 release and reboot development (or rather, maintenance) from there just to have a known solid starting point. There will be things to cherry-pick from the later work but there's also some pretty strange/suspect material in there and thoroughly evaluating all that is too much to start with.

**Comment by pmatilai** [comment]
@Conan-Kudo, @ffesti , others - I'm tempted to rename the actual master branch to something like old_master and then rename current popt-1.x to master to start over. Objections / thoughts / better ideas? 
A more lightweight option that doesn't involve forced pushes etc would be just changing the default branch to 1.x (or maint, or whatever) but then we'd have to live with that forever after, and "master" is wired pretty deep down in finger memory...

**Comment by Conan-Kudo** [comment]
@pmatilai If we wanted to restart development from the latest release and go forward, I could do the branch foo to restart master from 1.16 release and make the current master differently named...

I'm not particularly picky, but I'd hope we wouldn't waste the effort that was already done here...

**Comment by pmatilai** [comment]
Like said, there will be stuff to cherry-pick from the current master, possibly lots of it, but starting with six years worth developments to unknown directions is just too much to swallow at once. If we're to pick up popt maintenance, I see little other choice than rebooting at 1.16 and then cherry-pick at our own pace.

**Comment by pmatilai** [comment]
...so @Conan-Kudo , if you're okay with that, then please just do the branch-dance to make 1.16 release the new master, and then we can declare the hunting season open.

**Comment by Conan-Kudo** [comment]
@pmatilai Done!

**Comment by Conan-Kudo** [comment]
@pmatilai I preserved the old master branch as `rpm5-master`, so we can cherry-pick from there as needed.

**Comment by pmatilai** [comment]
Excellent, thanks!
