### ISSUE TITLE
main vs master branch?

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/popt#103]
Someone or something seems to have renamed the master branch to main in ... recent times. My local clone still has 'master' so it certainly was that way not too long ago.

[...]

@Conan-Kudo - GH audit log says you changed this in October. Was this by accident? Otherwise, I'd really like to know why you'd do such a thing without so much as discussing it with others first.

**Comment by Conan-Kudo** [comment]
Oops, it was an accident. I was fixing up a number of other projects I have around that time to switch to `main` since more than half of the projects I was contributing to already used it and it was getting to be a pain. I guess I did it on here rather than my fork. 😓

**Comment by pmatilai** [comment]
Ok, s*** happens. I do think we should switch it back through, I find branch renames on existing projects pretty antisocial.

**Comment by Conan-Kudo** [comment]
I wish GitHub let you set symrefs so that both could work, like we did in Fedora for `main` and `rawhide`...

**Comment by Conan-Kudo** [comment]
Actually, since this is a Git feature, I think _I_ can do that...

**Comment by Conan-Kudo** [comment]
I just pushed the `master` symref, it should work _exactly_ the same as `main` now.

**Comment by pmatilai** [comment]
Care to do the same trick for the popt-l10n repo? That's where I initially ran into this change, but then I brushed it aside 'nah must be misremembering something' :D

**Comment by Conan-Kudo** [comment]
Actually, it seems like it doesn't work? When I clone it down, the ref is pointing to a commit instead.

**Comment by Conan-Kudo** [comment]
Yeah, it doesn't work. 😩

**Comment by pmatilai** [comment]
Mm, that may have to do with it being a sub-module :thinking: Need to look into it all (but not today for me)

**Comment by Conan-Kudo** [comment]
I just changed popt back to `master` for now. We should discuss moving to `main` in the future though.

**Comment by pmatilai** [comment]
I quite dislike that main because it's just so non-descriptive and .. meh. There's one thing SVN got right: the thing from which branches grow from? It's trunk of course :smile:

**Comment by pmatilai** [comment]
I'll switch popt-l10n to master too because having these mixed up will just drive anybody crazy.

**Comment by pmatilai** [comment]
And okay, matter settled for now, thanks.

**Comment by Conan-Kudo** [comment]
Well, it is the _main_ branch and calling it the _mainline_ tree works when the branch is named "main", so it makes sense to me. 🤷🏾‍♂️ 

I also like the branch name is shorter. 😉
