### ISSUE TITLE
Migrate popt away from SemaphoreCI

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/popt#110]
From https://semaphoreci.com/blog/semaphore-classic-deprecation:

    However, we are excited to announce that Semaphore Classic will be discontinued by September 30, 2023.

It's an interesting way to put it. Okay, maybe their engineers are excited to be finally rid of a legacy platform that's pain to support, I can totally symphatize with that. At any rate, we need to move our business elsewhere before that.

We already migrated rpm (https://github.com/rpm-software-management/rpm/issues/2569) but forgot about popt.

**Comment by dmnks** [comment]
Done in the latest commit on master.
