### ISSUE TITLE
Add Conan 2 support for enhanced cross-platform compatibility

### ISSUE THREAD

**Issue by sobrito** [rpm-software-management/popt#111]
Hello team!

I've been using popt and noticed that Conan support has not yet been incorporated directly into the project. Given the significance of Conan as a package management tool for C++, I'd like to suggest its implementation in the project.

**Benefits of adding Conan 2 support:**
1. **Simplified Dependency Management:** Conan would streamline the integration and management of dependencies for C++ projects.
2. **Cross-Platform Compatibility:** Conan support could broaden the project's compatibility with different platforms, making it more accessible to a wider array of users.
3. **Testing Across Various Environments:** With Conan, it becomes simpler to test the project across different operating systems and compilers, ensuring greater robustness and stability.
4. **Attracting More Developers:** Supporting Conan can expand the user base, drawing in developers who use this tool for package management.
5. **Improved Recipe Maintenance:** While there is already Conan support in the Conan Center, having the recipe maintained directly by the project's developer can lead to quicker bug fixes and improvements. This ensures that the support is not just ported but is also kept up-to-date with the project's evolution.

I believe this addition would greatly benefit the community and the evolution of popt. I'd appreciate it if this suggestion were considered.

**Comment by pmatilai** [comment]
Sorry but no, we're not interested in supporting any package managers at upstream. We don't even carry a spec file for building an rpm, the package manager from which popt was spun out of!

You should really ask about things like this *before* spending a lot of time working on something that upstream categorically doesn't want.
