### ISSUE TITLE
CHANGES outdated – where is the changelog from 1.16 to 1.18?

### ISSUE THREAD

**Issue by RokerHRO** [rpm-software-management/popt#33]
I just got an update from 1.1.6 to 1.18 via Homebrew, but the CHANGELOG file I found here seems to be outdated.

**Comment by pmatilai** [comment]
https://github.com/rpm-software-management/popt/releases/tag/popt-1.18-release is the official release notes with that information.

The CHANGES file is not something we plan to maintain, but I agree it needs to at least state that it's for historical reference only, or maybe just drop it in favor of something automated from git.
