### ISSUE TITLE
Migrate translations to popt-l10n repo

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/popt#93]
To go with the cmake build (#74), lets split off the translations to a separate repo that we can hand over to Weblate and never bother with translation commits and PRs again.

https://github.com/rpm-software-management/popt-l10n repo created and populated with current translations, what remains is updating the weblate side to use that and then cut the umbilical on this side.

**Comment by Conan-Kudo** [comment]
popt-l10n will need to be resynced one last time to incorporate the cmake changes, but after that it should be good to go.
